version: "3.9"
services:
  app:
    build: .
    container_name: django_app_preprod
    restart: always

    environment:
      PORT: 8000
      DJANGO_SETTINGS_MODULE: yourproject.settings
    # OPENAI_API_KEY: ${OPENAI_API_KEY}

    env_file:
      - /opt/Study_assist_new_2.0/.env

    command: python manage.py runserver 0.0.0.0:8000

    ports:
      - "8000:8080"

    volumes:
      # persistent storage
      - uploads:/app/uploads
      - chromadb:/app/chroma_data

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/" ]
      interval: 30s
      timeout: 5s
      retries: 5

volumes:
  uploads:
  chromadb: